spring:
  config:
    import: optional:configserver:http://localhost:8080
  application:
    name: notification-ms
  mail:
    host: smtp.example.com
    port: 587
    username: example@mail.com
    password: password123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true