spring:
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@default.akmmhq0.mongodb.net/hiring_document?retryWrites=true&w=majority&appName=Default
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB
server:
  port: 8084