spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-ms
          uri: lb://AUTH-MS
          predicates:
            - Path=/api/auth/**
        - id: candidate-ms
          uri: lb://CANDIDATE-MS
          predicates:
            - Path=/api/candidate/**

server:
  port: 8222